#spring.application.name=shop_49
#spring.datasource.url=jdbc:postgresql://localhost:5432/g_49_shop
#spring.datasource.username=my_user
#spring.datasource.password=pos1234
#spring.datasource.driver-class-name=org.postgresql.Driver

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/shop_g49
    username: my_user
    password: pos1234
    driver-class-name: org.postgresql.Driver

  application:
    name: Shop

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml